---
workspace_dir: "{{ base_dir }}/workspace"
base_domain: aws.validatedpatterns.io
compute_replicas: 3
compute_type: m5.xlarge
controlplane_replicas: 3
controlplane_type: m5.xlarge
cluster_network_cidr: 10.128.0.0/14
cluster_network_hostprefix: 23
machine_network_cidr: 10.0.0.0/16
network_type: OVNKubernetes
service_network: 172.30.0.0/16

base64_cmd: "base64 -w0"
clusters_start_nr: 1
clusters_end_nr: "{{ clusters_count }}"

students_nginx_output: /var/www/html/


ssh_pub_file: ~/.ssh/id_rsa.pub
pull_secrets_file: ~/.pullsecret.json
